### ISSUE TITLE
TERENA certificate support to be fixed

### ISSUE THREAD

**Issue by bertocco** [opencadc/cdp#8]
Trying to delegate a terena user certificate with this command:
 java ca.nrc.cadc.cred.client.Main -d --delegate --daysValid=20 --cert=<terena_key_and_crt.pem>
It is thrown a ResourceNotFoundException
The reason is that the CSR is saved in the database (CertificateDAO.java, put method) with an hash key different to which used to retrieve it (DelegationsImpl.java, hash method).

Details:

CertificateDAO.java, put method, calculates the x509 certificate chain hash :
X509CertificateChain.getHashKey()

DelegationsImpl.java, in initializeIdentity method calls Delegations.hash, which calculates the principal hash:

public String hash(X500Principal principal)
    {
        return Integer.toString(principal.hashCode());
     }

Patch is to change this last method:

    public String hash(X500Principal principal)
    {
        return X509CertificateChain.getHashKey(principal);
    }

**Comment by pdowler** [comment]
That is a good bug find! Amazing/lucky that it worked for us for several years... I would accept this change that makes a consistent and controlled hash code computation. However, the actual implementation in X509CertificateChain is probably better because it puts the DN into canonical form first (rather than using the form in the X500Principal directly).  It looks like you chose that one so that looks good.

**Comment by pdowler** [comment]
hashCode bug in Delegations fixed in cadc-cdp-1.1.1 available on jcenter
